[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  framework = "#custom"
  publish = ".next"

[functions]
  node_bundler = "esbuild"

# Uncomment to use this redirect for Single Page Applications
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200